-- 1. Write a query to calculate the total revenue generated by each region.
;
-- 2. Display the names of employees earning a salary higher than the average salary in their department.
;
-- 3. Identify the second - highest salary in each department from the ‘ employees ’ table, which contains ‘ emp_id,’ ‘ department_id,’
--    and ‘ salary ’ columns.
;
-- 4. Write a SQL query to find employees who haven ’ t made any recent sales in the last 3 months.
;